<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('cbt_evaluations', function (Blueprint $table) {
            $table->id();            
            $table->string('examstatus')->nullable();
            $table->string('studentname')->nullable();
            $table->string('correct')->nullable(); 
            $table->string('noofquestion')->nullable();
            $table->string('wrong')->nullable();
            $table->string('studentno')->nullable();
            $table->string('score')->nullable();
            $table->string('level')->nullable();
            $table->string('session1')->nullable();
            $table->string('semester')->nullable();
            $table->integer('hour')->nullable();
            $table->integer('minute')->nullable();
            $table->string('qstno')->nullable();
            $table->integer('A1')->nullable();
            $table->integer('A2')->nullable();
            $table->integer('A3')->nullable();
            $table->integer('A4')->nullable();
            $table->integer('A5')->nullable();
            $table->integer('A6')->nullable();
            $table->integer('A7')->nullable();
            $table->integer('A8')->nullable();
            $table->integer('A9')->nullable();
            $table->integer('A10')->nullable();
            $table->integer('A11')->nullable();
            $table->integer('A12')->nullable();
            $table->integer('A13')->nullable();
            $table->integer('A14')->nullable();
            $table->integer('A15')->nullable();
            $table->integer('A16')->nullable();
            $table->integer('A17')->nullable();
            $table->integer('A18')->nullable();
            $table->integer('A19')->nullable();
            $table->integer('A20')->nullable();
            $table->integer('A21')->nullable();
            $table->integer('A22')->nullable();
            $table->integer('A23')->nullable();
            $table->integer('A24')->nullable();
            $table->integer('A25')->nullable();
            $table->integer('A26')->nullable();
            $table->integer('A27')->nullable();
            $table->integer('A28')->nullable();
            $table->integer('A29')->nullable();
            $table->integer('A30')->nullable();
            $table->integer('A31')->nullable();
            $table->integer('A32')->nullable();
            $table->integer('A33')->nullable();
            $table->integer('A34')->nullable();
            $table->integer('A35')->nullable();
            $table->integer('A36')->nullable();
            $table->integer('A37')->nullable();
            $table->integer('A38')->nullable();
            $table->integer('A39')->nullable();
            $table->integer('A40')->nullable();
            $table->integer('A41')->nullable();
            $table->integer('A42')->nullable();
            $table->integer('A43')->nullable();
            $table->integer('A44')->nullable();
            $table->integer('A45')->nullable();
            $table->integer('A46')->nullable();
            $table->integer('A47')->nullable();
            $table->integer('A48')->nullable();
            $table->integer('A49')->nullable();
            $table->integer('A50')->nullable();
            $table->integer('A51')->nullable();
            $table->integer('A52')->nullable();
            $table->integer('A53')->nullable();
            $table->integer('A54')->nullable();
            $table->integer('A55')->nullable();
            $table->integer('A56')->nullable();
            $table->integer('A57')->nullable();
            $table->integer('A58')->nullable();
            $table->integer('A59')->nullable();
            $table->integer('A60')->nullable();
            $table->integer('A61')->nullable();
            $table->integer('A62')->nullable();
            $table->integer('A63')->nullable();
            $table->integer('A64')->nullable();
            $table->integer('A65')->nullable();
            $table->integer('A66')->nullable();
            $table->integer('A67')->nullable();
            $table->integer('A68')->nullable();
            $table->integer('A69')->nullable();
            $table->integer('A70')->nullable();
            $table->integer('A71')->nullable();
            $table->integer('A72')->nullable();
            $table->integer('A73')->nullable();
            $table->integer('A74')->nullable();
            $table->integer('A75')->nullable();
            $table->integer('A76')->nullable();
            $table->integer('A77')->nullable();
            $table->integer('A78')->nullable();
            $table->integer('A79')->nullable();
            $table->integer('A80')->nullable();
            $table->integer('A81')->nullable();
            $table->integer('A82')->nullable();
            $table->integer('A83')->nullable();
            $table->integer('A84')->nullable();
            $table->integer('A85')->nullable();
            $table->integer('A86')->nullable();
            $table->integer('A87')->nullable();
            $table->integer('A88')->nullable();
            $table->integer('A89')->nullable();
            $table->integer('A90')->nullable();
            $table->integer('A91')->nullable();
            $table->integer('A92')->nullable();
            $table->integer('A93')->nullable();
            $table->integer('A94')->nullable();
            $table->integer('A95')->nullable();
            $table->integer('A96')->nullable();
            $table->integer('A97')->nullable();
            $table->integer('A98')->nullable();
            $table->integer('A99')->nullable();
            $table->integer('A100')->nullable();
            $table->string('department')->nullable();
            $table->string('exam_mode')->nullable();
            $table->string('exam_category')->nullable();
            $table->string('course')->nullable();
            $table->string('pageno')->nullable();
            $table->dateTime('examdate')->nullable();
            $table->string('exam_type')->nullable();
            $table->string('msgstatus')->nullable();
            $table->dateTime('starttime');
            $table->dateTime('endtime');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cbt_evaluations');
    }
};
