<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('cbt_evaluation2', function (Blueprint $table) {
            $table->id();
            $table->integer('examid');
            $table->text('examstatus')->nullable();
            $table->text('studentname')->nullable();
            $table->text('correct')->nullable();
            $table->text('noofquestion')->nullable();
            $table->text('wrong')->nullable();
            $table->text('studentno')->nullable();
            $table->text('subject1')->nullable();
            $table->text('score')->nullable();
            $table->text('date1')->nullable();
            $table->text('username')->nullable();
            $table->text('grade')->nullable();
            $table->text('class')->nullable();
            $table->text('session1')->nullable();
            $table->text('term')->nullable();
            $table->text('parentphoneno')->nullable();
            $table->text('percentage')->nullable();
            $table->text('partno')->nullable();
            $table->text('credits')->nullable();
            $table->text('timein')->nullable();
            $table->text('timeout')->nullable();
            $table->text('hour')->nullable();
            $table->text('minute')->nullable();
            $table->text('qstno')->nullable();
            $table->integer('OK1')->nullable();
            $table->integer('OK2')->nullable();
            $table->integer('OK3')->nullable();
            $table->integer('OK4')->nullable();
            $table->integer('OK5')->nullable();
            $table->integer('OK6')->nullable();
            $table->integer('OK7')->nullable();
            $table->integer('OK8')->nullable();
            $table->integer('OK9')->nullable();
            $table->integer('OK10')->nullable();
            $table->integer('OK11')->nullable();
            $table->integer('OK12')->nullable();
            $table->integer('OK13')->nullable();
            $table->integer('OK14')->nullable();
            $table->integer('OK15')->nullable();
            $table->integer('OK16')->nullable();
            $table->integer('OK17')->nullable();
            $table->integer('OK18')->nullable();
            $table->integer('OK19')->nullable();
            $table->integer('OK20')->nullable();
            $table->integer('OK21')->nullable();
            $table->integer('OK22')->nullable();
            $table->integer('OK23')->nullable();
            $table->integer('OK24')->nullable();
            $table->integer('OK25')->nullable();
            $table->integer('OK26')->nullable();
            $table->integer('OK27')->nullable();
            $table->integer('OK28')->nullable();
            $table->integer('OK29')->nullable();
            $table->integer('OK30')->nullable();
            $table->integer('OK31')->nullable();
            $table->integer('OK32')->nullable();
            $table->integer('OK33')->nullable();
            $table->integer('OK34')->nullable();
            $table->integer('OK35')->nullable();
            $table->integer('OK36')->nullable();
            $table->integer('OK37')->nullable();
            $table->integer('OK38')->nullable();
            $table->integer('OK39')->nullable();
            $table->integer('OK40')->nullable();
            $table->integer('OK41')->nullable();
            $table->integer('OK42')->nullable();
            $table->integer('OK43')->nullable();
            $table->integer('OK44')->nullable();
            $table->integer('OK45')->nullable();
            $table->integer('OK46')->nullable();
            $table->integer('OK47')->nullable();
            $table->integer('OK48')->nullable();
            $table->integer('OK49')->nullable();
            $table->integer('OK50')->nullable();
            $table->integer('OK51')->nullable();
            $table->integer('OK52')->nullable();
            $table->integer('OK53')->nullable();
            $table->integer('OK54')->nullable();
            $table->integer('OK55')->nullable();
            $table->integer('OK56')->nullable();
            $table->integer('OK57')->nullable();
            $table->integer('OK58')->nullable();
            $table->integer('OK59')->nullable();
            $table->integer('OK60')->nullable();
            $table->integer('OK61')->nullable();
            $table->integer('OK62')->nullable();
            $table->integer('OK63')->nullable();
            $table->integer('OK64')->nullable();
            $table->integer('OK65')->nullable();
            $table->integer('OK66')->nullable();
            $table->integer('OK67')->nullable();
            $table->integer('OK68')->nullable();
            $table->integer('OK69')->nullable();
            $table->integer('OK70')->nullable();
            $table->integer('OK71')->nullable();
            $table->integer('OK72')->nullable();
            $table->integer('OK73')->nullable();
            $table->integer('OK74')->nullable();
            $table->integer('OK75')->nullable();
            $table->integer('OK76')->nullable();
            $table->integer('OK77')->nullable();
            $table->integer('OK78')->nullable();
            $table->integer('OK79')->nullable();
            $table->integer('OK80')->nullable();
            $table->integer('OK81')->nullable();
            $table->integer('OK82')->nullable();
            $table->integer('OK83')->nullable();
            $table->integer('OK84')->nullable();
            $table->integer('OK85')->nullable();
            $table->integer('OK86')->nullable();
            $table->integer('OK87')->nullable();
            $table->integer('OK88')->nullable();
            $table->integer('OK89')->nullable();
            $table->integer('OK90')->nullable();
            $table->integer('OK91')->nullable();
            $table->integer('OK92')->nullable();
            $table->integer('OK93')->nullable();
            $table->integer('OK94')->nullable();
            $table->integer('OK95')->nullable();
            $table->integer('OK96')->nullable();
            $table->integer('OK97')->nullable();
            $table->integer('OK98')->nullable();
            $table->integer('OK99')->nullable();
            $table->integer('OK100')->nullable(); 
            $table->text('department')->nullable();
            $table->text('pageno')->nullable();
            $table->text('subject2')->nullable();
            $table->text('subject3')->nullable();
            $table->text('subject4')->nullable();
            $table->text('subject5')->nullable();
            $table->text('score1')->nullable();
            $table->text('score2')->nullable();
            $table->text('score3')->nullable();
            $table->text('score4')->nullable();
            $table->text('score5')->nullable();
            $table->text('examdate')->nullable();
            $table->text('examdate1')->nullable();
            $table->text('examtype')->nullable();
            $table->text('msgstatus')->nullable();
            $table->dateTime('starttime');
            $table->dateTime('endtime');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cbt_evaluation2');
    }
};
