<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('cbt_evaluation2', function (Blueprint $table) {
            $table->id();
            $table->text('examstatus')->nullable();
            $table->text('studentname')->nullable();
            $table->text('correct')->nullable();
            $table->text('noofquestion')->nullable();
            $table->text('wrong')->nullable();
            $table->text('studentno')->nullable();
            $table->text('score')->nullable();
            $table->text('level')->nullable();
            $table->text('session1')->nullable();
            $table->text('semester')->nullable();
            $table->integer('hour')->nullable();
            $table->integer('minute')->nullable();
            $table->text('qstno')->nullable();
            $table->text('OK1')->nullable();
            $table->text('OK2')->nullable();
            $table->text('OK3')->nullable();
            $table->text('OK4')->nullable();
            $table->text('OK5')->nullable();
            $table->text('OK6')->nullable();
            $table->text('OK7')->nullable();
            $table->text('OK8')->nullable();
            $table->text('OK9')->nullable();
            $table->text('OK10')->nullable();
            $table->text('OK11')->nullable();
            $table->text('OK12')->nullable();
            $table->text('OK13')->nullable();
            $table->text('OK14')->nullable();
            $table->text('OK15')->nullable();
            $table->text('OK16')->nullable();
            $table->text('OK17')->nullable();
            $table->text('OK18')->nullable();
            $table->text('OK19')->nullable();
            $table->text('OK20')->nullable();
            $table->text('OK21')->nullable();
            $table->text('OK22')->nullable();
            $table->text('OK23')->nullable();
            $table->text('OK24')->nullable();
            $table->text('OK25')->nullable();
            $table->text('OK26')->nullable();
            $table->text('OK27')->nullable();
            $table->text('OK28')->nullable();
            $table->text('OK29')->nullable();
            $table->text('OK30')->nullable();
            $table->text('OK31')->nullable();
            $table->text('OK32')->nullable();
            $table->text('OK33')->nullable();
            $table->text('OK34')->nullable();
            $table->text('OK35')->nullable();
            $table->text('OK36')->nullable();
            $table->text('OK37')->nullable();
            $table->text('OK38')->nullable();
            $table->text('OK39')->nullable();
            $table->text('OK40')->nullable();
            $table->text('OK41')->nullable();
            $table->text('OK42')->nullable();
            $table->text('OK43')->nullable();
            $table->text('OK44')->nullable();
            $table->text('OK45')->nullable();
            $table->text('OK46')->nullable();
            $table->text('OK47')->nullable();
            $table->text('OK48')->nullable();
            $table->text('OK49')->nullable();
            $table->text('OK50')->nullable();
            $table->text('OK51')->nullable();
            $table->text('OK52')->nullable();
            $table->text('OK53')->nullable();
            $table->text('OK54')->nullable();
            $table->text('OK55')->nullable();
            $table->text('OK56')->nullable();
            $table->text('OK57')->nullable();
            $table->text('OK58')->nullable();
            $table->text('OK59')->nullable();
            $table->text('OK60')->nullable();
            $table->text('OK61')->nullable();
            $table->text('OK62')->nullable();
            $table->text('OK63')->nullable();
            $table->text('OK64')->nullable();
            $table->text('OK65')->nullable();
            $table->text('OK66')->nullable();
            $table->text('OK67')->nullable();
            $table->text('OK68')->nullable();
            $table->text('OK69')->nullable();
            $table->text('OK70')->nullable();
            $table->text('OK71')->nullable();
            $table->text('OK72')->nullable();
            $table->text('OK73')->nullable();
            $table->text('OK74')->nullable();
            $table->text('OK75')->nullable();
            $table->text('OK76')->nullable();
            $table->text('OK77')->nullable();
            $table->text('OK78')->nullable();
            $table->text('OK79')->nullable();
            $table->text('OK80')->nullable();
            $table->text('OK81')->nullable();
            $table->text('OK82')->nullable();
            $table->text('OK83')->nullable();
            $table->text('OK84')->nullable();
            $table->text('OK85')->nullable();
            $table->text('OK86')->nullable();
            $table->text('OK87')->nullable();
            $table->text('OK88')->nullable();
            $table->text('OK89')->nullable();
            $table->text('OK90')->nullable();
            $table->text('OK91')->nullable();
            $table->text('OK92')->nullable();
            $table->text('OK93')->nullable();
            $table->text('OK94')->nullable();
            $table->text('OK95')->nullable();
            $table->text('OK96')->nullable();
            $table->text('OK97')->nullable();
            $table->text('OK98')->nullable();
            $table->text('OK99')->nullable();
            $table->text('OK100')->nullable();
            $table->text('department')->nullable();
            $table->text('exam_mode')->nullable();
            $table->text('exam_category')->nullable();
            $table->text('course')->nullable();
            $table->text('pageno')->nullable();
            $table->dateTime('examdate')->nullable();
            $table->text('exam_type')->nullable();
            $table->text('msgstatus')->nullable();
            $table->dateTime('starttime');
            $table->dateTime('endtime');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cbt_evaluation2');
    }
};
